#!/usr/bin/env bash
# cd ~
# curl -o installProxy.sh https://raw.githubusercontent.com/devslaweekq/utils/main/tgproxy/install.sh
# chmod +x installProxy.sh
# sudo ./installProxy.sh

#
# Installation of a SOCKS5 proxy with authentication (Dante) on Ubuntu.
# Suitable for use with Telegram (SOCKS5 + username/password).

set -euo pipefail

info()  { printf "\033[1;34m[INFO]\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m[WARN]\033[0m %s\n" "$*"; }
error() { printf "\033[1;31m[ERR ]\033[0m %s\n" "$*"; }

ask_default() {
  local prompt="$1"
  local default="${2-}"
  local value
  if [[ -n "${default}" ]]; then
    read -r -p "$prompt [$default]: " value
    value="${value:-$default}"
  else
    read -r -p "$prompt: " value
  fi
  printf '%s' "$value"
}

if [[ $EUID -ne 0 ]]; then
  error "Run this script as root, for example: sudo $0"
  exit 1
fi

if [[ -f /etc/os-release ]]; then
  . /etc/os-release
  if [[ "${ID:-}" != "ubuntu" && "${ID_LIKE:-}" != *"ubuntu"* ]]; then
    warn "This script was tested on Ubuntu. Continuing at your own risk."
  fi
fi

echo "=== Configuring SOCKS5 proxy (Dante) ==="

PROXY_PORT="$(ask_default 'SOCKS5 port on the server' '8288')"
PROXY_USER="$(ask_default 'Username for proxy access' 'proxyuser')"

while true; do
  read -r -s -p "Password for proxy access: " PROXY_PASS_1
  echo
  read -r -s -p "Repeat password: " PROXY_PASS_2
  echo
  if [[ "$PROXY_PASS_1" != "$PROXY_PASS_2" ]]; then
    warn "Passwords do not match, please try again."
  elif [[ -z "$PROXY_PASS_1" ]]; then
    warn "Password cannot be empty."
  else
    break
  fi
done

NET_IFACE_DEFAULT="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}' || echo 'eth0')"
NET_IFACE="$(ask_default 'Network interface to accept connections from (usually eth0/ens3/ens160)' "$NET_IFACE_DEFAULT")"

# By default allow all IPv4 clients to use the proxy.
# You can restrict this later in /etc/danted.conf if needed.
# ALLOW_SUBNET_DEFAULT="$(ip -4 addr show "$NET_IFACE" 2>/dev/null | awk '/inet / {print $2; exit}' || echo '0.0.0.0/0')"

ALLOW_SUBNET_DEFAULT="0.0.0.0/0"
ALLOW_SUBNET="$(ask_default 'Subnet allowed to use the proxy (for example 0.0.0.0/0 or 10.0.0.0/24)' "$ALLOW_SUBNET_DEFAULT")"

echo
info "Parameters:"
echo "  Port:           $PROXY_PORT"
echo "  Username:       $PROXY_USER"
echo "  Interface:      $NET_IFACE"
echo "  Allowed subnet: $ALLOW_SUBNET"
echo

###############################################################################
# Package installation
###############################################################################

info "Updating packages and installing dante-server..."
apt update -y
apt install -y dante-server

###############################################################################
# Creating a system user for SOCKS authentication
###############################################################################

if id "$PROXY_USER" >/dev/null 2>&1; then
  warn "User $PROXY_USER already exists, updating password."
else
  info "Creating system user $PROXY_USER without shell."
  useradd -r -s /usr/sbin/nologin "$PROXY_USER"
fi

echo "${PROXY_USER}:${PROXY_PASS_1}" | chpasswd

###############################################################################
# Dante configuration (/etc/danted.conf)
###############################################################################

info "Writing configuration to /etc/danted.conf..."

cat >/etc/danted.conf <<EOF
# Automatically generated by install.sh

logoutput: syslog

internal: ${NET_IFACE} port = ${PROXY_PORT}
external: ${NET_IFACE}

clientmethod: none
socksmethod: username

user.notprivileged: nobody

client pass {
    from: ${ALLOW_SUBNET} to: 0.0.0.0/0
    log: connect disconnect error
}

client block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect error
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect disconnect error
}

EOF

###############################################################################
# Start and enable service
###############################################################################

info "Restarting danted service..."
systemctl restart danted
systemctl enable danted

sleep 1
if ! systemctl is-active --quiet danted; then
  error "The danted service did not start. Check 'systemctl status danted' and 'journalctl -u danted'."
  exit 1
fi

SERVER_IP="$(curl -s https://api.ipify.org || hostname -I | awk '{print $1}')"

echo
info "Done! SOCKS5 proxy is running."
echo
echo "=== Settings for Telegram ==="
echo "  Proxy type:     SOCKS5"
echo "  Server (IP):    ${SERVER_IP}"
echo "  Port:           ${PROXY_PORT}"
echo "  Username:       ${PROXY_USER}"
echo "  Password:       (the one you entered)"
echo
echo "=== Test from the server ==="
echo "  curl -v -x socks5://${PROXY_USER}:${PROXY_PASS_1}@127.0.0.1:${PROXY_PORT} http://t.me"
echo
info "If interface/port/subnet changes, just run this script again."
